# escape=`

FROM lacledeslan/gamesvr-srcds-tf2:linux

LABEL maintainer "Laclede's LAN <contact@lacledeslan.com>"

ENV IMAGE="gamesvr-srcds-tf2-blindfrag:linux"

HEALTHCHECK NONE

USER root

COPY ./dist /app/bin/

COPY ./dist.linux /app/bin/tf/

# CLEAN UP
RUN usermod -l TF2.BlindFrag TF2

USER TF2.BlindFrag
	
WORKDIR /app/bin/
