# escape=`

FROM lacledeslan/gamesvr-tf2

LABEL maintainer "Laclede's LAN <contact@lacledeslan.com>"

ENV IMAGE="gamesvr-tf2-blindfrag"

HEALTHCHECK NONE

COPY ./dist /app/tf/

COPY ./dist.linux /app/tf/

# UPDATE USERNAME
RUN usermod -l TF2BlindFrag TF2

USER TF2BlindFrag

WORKDIR /app/
